config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'ipods#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :ipods, only: [ :index, :show, :new, :create, :update, :edit ] do
    resources :purchases, only: [ :new, :create ]
  end
  resources :users, only: [ :new, :create, :show ]
  resources :categories, only: [ :show ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :ipods
  after_validation :set_slug

  def set_slug
    self.slug = name.parameterize
  end

  def to_param
    "#{self.id}-#{self.slug}"
  end
end

app/models/ipod.rb
class Ipod < ApplicationRecord
  belongs_to :user
  has_many :purchases
  belongs_to :category
  has_one_attached :photo

  validates :name, :description, :color, :state, :capacity, :price, presence: true
  validates :name, length: { minimum: 4 }
  validates :description, length: { minimum: 6 }
  # validates :model, inclusion: {
  #   in: ['iPod Classic', 'iPod Mini', 'iPod Nano', 'iPod Shuffle', 'iPod Touch']
  # }
  validates :color, inclusion: {
    in: %w[Grey Black White Blue Green Pink]
  }
  validates :state, inclusion: {
    in: %w[Fair Good Excellent]
  }
  validates :capacity, inclusion: {
    in: [16, 32, 64, 128, 256]
  }

  include PgSearch::Model
  pg_search_scope :search_by_name_and_model,
    against: [ :name, :model ],
    using: {
      tsearch: { prefix: true }
    }
end

app/models/purchase.rb
class Purchase < ApplicationRecord
  belongs_to :user
  belongs_to :ipod

  enum state: [:available, :pending, :approved]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :ipods #ipods that this user owns
  #has_many :ipods, through: :purchases
  has_many :purchases
  has_one_attached :photo

  validates :first_name, :last_name, :email, :password, presence: true
  # validates :first_name, :last_name, :email, :password, allow_blank: false
  validates :email, uniqueness: true
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :photo])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @category = Category.find(params[:id])
  end
end

app/controllers/ipods_controller.rb
class IpodsController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :index, :show ]

  def index
    # @ipods = Ipod.all
    @categories = Category.all
    if params[:query].present?
      @ipods = Ipod.search_by_name_and_model(params[:query])
    else
      @ipods = Ipod.all
    end
  end

  def show
    @ipod = Ipod.find(params[:id])
  end

  def new
    @ipod = Ipod.new
  end

  def create
    @ipod = Ipod.new(ipod_params)
    @ipod.user = current_user
    if @ipod.save
      redirect_to ipod_path(@ipod)
    else
      render :new
    end
  end

  def edit
    @ipod = Ipod.find(params[:id])
  end

  def update
    @ipod = Ipod.find(params[:id])
    if @ipod.update(ipod_params)
      redirect_to ipod_path(@ipod)
    else
      render :edit
    end
  end

  private

  def ipod_params
    params.require(:ipod).permit(:name, :description, :category_id, :color, :state, :photo, :price, :capacity)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home, :show ]

  def home
  end
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  def new
    @ipod = Ipod.find(params[:ipod_id])
    @purchase = Purchase.new
  end

  def create
    @purchase = Purchase.new(purchase_params)
    @ipod = Ipod.find(params[:ipod_id])
    @purchase.ipod = @ipod
    @purchase.user = current_user
    @purchase.state = 1
    if @purchase.save
      redirect_to user_path(current_user)
    else
      render :new
    end
  end

  private

  def purchase_params
    params.require(:purchase).permit(:delivery_address, :phone_number, :message)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

  def create
  end

  def show
    #ipods that current_user is selling
    @selling = current_user.ipods
    #ipods that current user has bought
    @purchases = current_user.purchases
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/show.html.erb
<div class="container d-flex mb-4 text-bg-dark hero">
  <div class="col-md-5 px-0 my-auto hero-content">
    <h1><%= @category.name %></h1>
    <p class="lead my-3">All <%= @category.name %> are displayed here.</p>
  </div>
</div>

<div class="section content" id="index">
  <div class="row mb-3">
    <% @category.ipods.each do |ipod| %>
      <div class="col-md-3">
        <div class="card">
          <% if ipod.photo.attached? %>
            <div class="card-img-top-wrapper">
              <span class="card-text-model"><%= ipod.category.name %></span>
              <%= cl_image_tag ipod.photo.key, class:'card-img-top' %>
            </div>
          <% else %>
            <div class="card-img-top-wrapper">
              <span class="card-text-model"><%= ipod.category.name %></span>
              <%= image_tag "#{ipod.category.name}.jpg", class:'card-img-top' %>
            </div>
          <% end %>
          <div class="card-body">
            <h5 class="card-title"><%= ipod.name %></h5>
            <span class="card-text"><%= ipod.description %></span>
            <div class="d-flex justify-content-between align-items-center mt-2">
              <span class="price"><%= ipod.price %>€</span>
              <div class="color d-inline-flex">
                <span class="card-text me-2">color:</span>
                <% if ipod.color == 'White' %>
                  <div class="color-white"></div>
                <% elsif ipod.color == 'Grey' %>
                  <div class="color-grey"></div>
                <% elsif ipod.color == 'Black' %>
                  <div class="color-black"></div>
                <% elsif ipod.color == 'Blue' %>
                  <div class="color-blue"></div>
                <% elsif ipod.color == 'Green' %>
                  <div class="color-green"></div>
                <% elsif ipod.color == 'Pink' %>
                  <div class="color-pink"></div>
                <% end %>
              </div>
            </div>
            <div class="action-row">
              <%= link_to ipod_path(ipod), class:'btn btn-dark me-2' do %>
                <%= image_tag 'icon-eye.svg', alt: 'show icon', class: 'action-icon' %>
              <% end %>
              <%= link_to new_ipod_purchase_path(ipod), class:'btn btn-dark' do %>
                <%= image_tag 'icon-shop.svg', alt: 'buy icon', class: 'action-icon' %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>
</section>
<section class="container reviews">
  <div class="row">
    <div class="col">
      <div class="reviews-image"></div>
    </div>
    <div class="col">
      <div class="reviews-carousel">
        <span class="flag mb-3">Reviews</span>
        <span class="trusted-content mb-2">Shop with confidance by reading customer
              reviews given by individuals who have used
              applepie. Excelent quality and streamlined
              service are both offered here.
        </span>
        <%= image_tag 'reviews-star.svg', alt: 'rating stars', class: 'rating-stars mb-3' %>
        <span class="counter mb-3">2.479 reviews</span>
        <h3 class="review-content">Great iPod, however the headphone is giving me problems, I hope it's nothing but if it continues I'll get it checked</h3>
        <span class="author">Michael P.</span>
        <span class="locale">Lake Forest, CA</span>
      </div>
    </div>
  </div>
</section>

app/views/ipods/edit.html.erb
<div class="row">
  <div class="col-6 p-5">
    <% if @ipod.photo.attached? %>
      <div class="card-img-top-wrapper">
        <%= cl_image_tag @ipod.photo.key, class:'card-img' %>
      </div
    <% else %>
      <div class="card-img-top-wrapper">
        <%= image_tag "#{@ipod.category.name}.jpg", class:'card-img' %>
      </div>
    <% end %>
  </div>
    <div class="col-6 p-5">
      <h1>Update your iPod</h1>
      <p>This iPod will be updated right away.</p>

      <%= simple_form_for @ipod do |f| %>
        <div class="row g-3 ">
          <div class="col-12">
            <%= f.input :name %>
          </div>
          <div class="col-12 mt-0">
            <%= f.input :description %>
          </div>
          <div class="col-6 mt-0">
            <%= f.association :category %>  <%# Choose between pre-defined models %>
          </div>
          <div class="col-6 mt-0">
            <%= f.input :color, collection: [ "Grey", "Black", "White", "Blue", "Green", "Pink" ] %>  <%# Choose between pre-defined colors %>
          </div>
          <div class="col-4 mt-0">
            <%= f.input :capacity, collection: [ 16, 32, 64, 128, 256 ] %>  <%# Choose between pre-defined capacities %>
          </div>
          <div class="col-4 mt-0">
            <%= f.input :state, collection: [ "Fair", "Good", "Excellent" ] %> <%# Choose between pre-defined states %>
          </div>
          <div class="col-4 mt-0">
            <%= f.input :price %>
          </div>
          <div class="col-12 mt-0">
            <%= f.input :photo, as: :file %>
          </div>
          <div class="d-grid">
            <%= f.submit "Update", class: "btn btn-dark" %>
          </div>
        </div>
      <% end %>
    </div>
</div>

app/views/ipods/index.html.erb
<div class="container d-flex mb-4 text-bg-dark hero">
  <div class="col-md-5 px-0 my-auto hero-content">
    <h1>Your sweet spot for iPods.</h1>
    <p class="lead my-3">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Doloremque, quisquam perferendis!</p>
    <%= link_to "Start selling", new_ipod_path, class:'btn btn-dark mt-3'  %>
  </div>
</div>

<div class="container">
<div class="section content" id="index">
  <div class="d-flex my-5 justify-content-between">
    <% @categories.each do |category| %>
      <%= link_to category.name, category_path(category), class:'btn btn-outline-dark'  %>
    <% end %>
  </div>
    <div class="d-flex justify-content-between mb-4">
      <div class="row">
        <div class="col-8">
          <span class="section-highline">Our shop</span>
          <h3 class="section-title mb-2">Here are our best seller from the stock</h3>
        </div>
      </div>
      <div class="row g-2 mb-3 align-items-end">
          <div class="col-auto">
            <%= form_tag ipods_path(anchor: "index"), method: :get do %>
            <%= text_field_tag :query,
              params[:query],
              class: "form-control",
              placeholder: "Find an iPod"
            %>
          </div>
          <div class="col-auto">
            <%= submit_tag "Search", class: "btn btn-dark" %>
            <% end %>
          </div>
      </div>
    </div>
  <div class="row mb-3">
    <% @ipods.each do |ipod| %>
      <div class="col-md-3">
        <div class="card">
          <% if ipod.photo.attached? %>
            <div class="card-img-top-wrapper">
              <span class="card-text-model"><%= ipod.category.name %></span>
              <%= cl_image_tag ipod.photo.key, class:'card-img-top' %>
            </div>
          <% else %>
            <div class="card-img-top-wrapper">
              <span class="card-text-model"><%= ipod.category.name %></span>
              <%= image_tag "#{ipod.category.name}.jpg", class:'card-img-top' %>
            </div>
          <% end %>
          <div class="card-body">
            <h5 class="card-title"><%= ipod.name %></h5>
            <span class="card-text"><%= ipod.description %></span>
            <div class="d-flex justify-content-between align-items-center mt-2">
              <span class="price"><%= ipod.price %>€</span>
              <div class="color d-inline-flex">
                <span class="card-text me-2">color:</span>
                <% if ipod.color == 'White' %>
                  <div class="color-white"></div>
                <% elsif ipod.color == 'Grey' %>
                  <div class="color-grey"></div>
                <% elsif ipod.color == 'Black' %>
                  <div class="color-black"></div>
                <% elsif ipod.color == 'Blue' %>
                  <div class="color-blue"></div>
                <% elsif ipod.color == 'Green' %>
                  <div class="color-green"></div>
                <% elsif ipod.color == 'Pink' %>
                  <div class="color-pink"></div>
                <% end %>
              </div>
            </div>
            <div class="action-row">
              <%= link_to ipod_path(ipod), class:'btn btn-dark me-2' do %>
                <%= image_tag 'icon-eye.svg', alt: 'show icon', class: 'action-icon' %>
              <% end %>
              <%= link_to new_ipod_purchase_path(ipod), class:'btn btn-dark' do %>
                <%= image_tag 'icon-shop.svg', alt: 'buy icon', class: 'action-icon' %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>
</section>
<section class="container d-flex mb-4 text-bg-dark hero-content-sm">
  <div class="col-md-4 px-0 hero-content">
    <h1>Get inspired from our Instagram</h1>
    <p class="lead my-3">If you use the hashtag #applepie on Instagram, we’ll spotlight you.</p>
    <span class="call-to-action">Check it out</span>
  </div>
</section>
<section class="container reviews">
  <div class="row">
    <div class="col">
      <div class="reviews-image"></div>
    </div>
    <div class="col">
      <div class="reviews-carousel">
        <span class="flag mb-3">Reviews</span>
        <span class="trusted-content mb-2">Shop with confidance by reading customer
              reviews given by individuals who have used
              applepie. Excelent quality and streamlined
              service are both offered here.
        </span>
        <%= image_tag 'reviews-star.svg', alt: 'rating stars', class: 'rating-stars mb-3' %>
        <span class="counter mb-3">2.479 reviews</span>
        <h3 class="review-content">Great iPod, however the headphone is giving me problems, I hope it's nothing but if it continues I'll get it checked</h3>
        <span class="author">Michael P.</span>
        <span class="locale">Lake Forest, CA</span>
      </div>
    </div>
  </div>
</section>
<footer class="footer">
    <%= image_tag 'applepie-logotype.svg', alt: 'Applepie logotype', class: 'logotype' %>
    <span class="copyright">Copyright © 2022 applepie All rights Reserved.</span>
</footer>

app/views/ipods/new.html.erb
<div class="container">
  <div class="row my-5">
    <div class="col-6">
      <%= image_tag "new-page.jpg", class: "card-img" %>
    </div>
    <div class="col-5 ps-5 mt-2">
      <h1>List a new iPod</h1>
      <p>This iPod will be listed on the platform.</p>
      <%= simple_form_for @ipod do |f| %>
        <div class="row g-3 ">
          <div class="col-12">
            <%= f.input :name %>
          </div>
          <div class="col-12 mt-0">
            <%= f.input :description %>
          </div>
          <div class="col-6 mt-0">
            <%= f.association :category %>  <%# Choose between pre-defined models %>
          </div>
          <div class="col-6 mt-0">
            <%= f.input :color, collection: [ "Grey", "Black", "White", "Blue", "Green", "Pink" ] %>  <%# Choose between pre-defined colors %>
          </div>
          <div class="col-4 mt-0">
            <%= f.input :capacity, collection: [ 16, 32, 64, 128, 256 ] %>  <%# Choose between pre-defined capacities %>
          </div>
          <div class="col-4 mt-0">
            <%= f.input :state, collection: [ "Fair", "Good", "Excellent" ] %> <%# Choose between pre-defined states %>
          </div>
          <div class="col-4 mt-0">
            <%= f.input :price %>
          </div>
          <div class="col-12 mt-0">
            <%= f.input :photo, as: :file %>
          </div>
          <div class="d-grid">
            <%= f.submit "Create", class: "btn btn-dark py-2" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/ipods/show.html.erb
<div class="container">
  <div class="row my-5 show-page">
    <div class="col-6">
      <% if @ipod.photo.attached? %>
        <%= cl_image_tag @ipod.photo.key, class:'card-img' %>
      <% else %>
        <%= image_tag "#{@ipod.category.name}.jpg", class:'card-img'  %>
      <% end %>
    </div>
    <div class="col-5 ps-5 mt-2">
      <div class="d-flex align-items-center mb-2">
        <%= image_tag 'icon-cash.svg', alt: 'money icon', class: 'icon-lg' %>
        <h5 class="show-price"><%= @ipod.price %>€</h5>
      </div>
      <h1 class="text-uppercase"><%= @ipod.name %></h1>
      <p class="text-muted"><%= @ipod.description %></p>
      <p class="h6 font-weight-light text-muted text-uppercase mt-4">Details</p>
      <div class="d-flex mt-3">
        <p class="me-2"><span class="title">Model:</span> <%= @ipod.category.name %></p>
      </div>
      <div class="d-flex">
        <p class="me-2"><span class="title">State:</span> <%= @ipod.state %></p>
      </div>
      <div class="d-flex">
        <p class="me-2"><span class="title">Color:</span> <%= @ipod.color %></p>
      </div>
      <div class="d-flex">
        <p class="me-2"><span class="title">Capacity:</span> <%= @ipod.capacity %></p>
      </div>

      <div class="mt-4">
        <%= link_to new_ipod_purchase_path(@ipod), class:'btn btn-dark w-100 mb-2 py-2' do %>
          <%= image_tag 'icon-shop.svg', alt: 'buy icon', class: 'show-action-icon' %>
          <span>Buy</span>
        <% end %>
        <%= link_to 'Back to list', ipods_path, class:'btn btn-outline-dark w-100 py-2' %>
      </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Applepie</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Rubik:wght@300;400;500;700&display=swap" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <div>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= render 'shared/flashes' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/purchases/create.html.erb
<h1>Purchases#create</h1>
<p>Find me in app/views/purchases/create.html.erb</p>

app/views/purchases/new.html.erb
<div class="container">
  <h1>Complete your purchase</h1>
  <%= simple_form_for [@ipod, @purchase] do |f| %>
    <%= f.input :delivery_address %>
    <%= f.input :phone_number %>
    <%= f.input :message %>
    <%= f.submit "Buy", class: "btn btn-dark" %>
  <% end %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="container">
  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "applepie-logotype.svg" %>
    <% end %>

    <div class="row align-items-center">
      <div class="col-3 navbar-nav">
        <%= link_to new_ipod_path, class: "icon" do %>
          <%= image_tag "icon-new.svg" %>
        <% end %>
      </div>

      <div class="col-3 navbar-nav">
        <%= link_to edit_user_registration_path, class: "icon" do %>
          <%= image_tag "icon-edit.svg" %>
        <% end %>
      </div>

      <div class="col-6">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto">
            <% if user_signed_in? %>
              <li class="nav-item dropdown">
                <% if current_user.photo.attached? %>
                  <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
                <% else %>
                  <%= image_tag "iPod Classic.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
                <% end %>
                <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                  <%= link_to "Profile", user_path(current_user), class: "dropdown-item" %>
                  <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
                </div>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to "Login", new_user_session_path, class: "btn btn-outline-dark" %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<div class="hero-profile-banner"></div>
<div class="profile-data container">
  <div class="d-flex flex-column">
    <%= image_tag 'user-profile-icon.svg', alt: 'show icon', class: 'profile-icon' %>
    <span class="my-account">my account</span>
  </div>
  <div class="profile-data-content">
    <div class="profile-avatar">
      <% if user_signed_in? %>
        <% if current_user.photo.attached? %>
          <%= cl_image_tag current_user.photo.key, class: "profile-page-avatar", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <% else %>
          <%= image_tag "iPod Classic.jpg", class: "profile-page-avatar", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <% end %>
        <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
          <%= link_to "Profile", user_path(current_user), class: "dropdown-item" %>
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
        </div>
      <% end %>
      <%= link_to edit_user_registration_path do %>
        <%= image_tag "icon-edit-white.svg", class: "profile-page-avatar-edit" %>
      <% end %>
    </div>
    <p class="user-name"><%= current_user.first_name %> <%= current_user.last_name %></p>
    <span class="user-email"><%= current_user.email %></span>
  </div>
</div>

<div class="container-profile">
  <div class="purchases">
    <div class="tag">
      <%= image_tag 'icon-shop.svg', alt: 'show icon', class: 'shop-icon' %>
      <span>My purchases</span>
    </div>
  </div>
  <% current_user.purchases.each do |purchase| %>
    <div class="card-horizontal">
      <div class="d-flex justify-content-between">
        <span class="purchase-status"><%= purchase.state %></span>
        <span class="purchase-price"><%= purchase.ipod.price %>€</span>
      </div>
      <div class="d-flex flex-column mb-4">
        <h3 class="ipod-name"><%= purchase.ipod.name %></h3>
        <span class="purchase-details"><span class="purchase-details-title">Address: </span><%= purchase.delivery_address %></span>
        <span class="purchase-details"><span class="purchase-details-title">Phone: </span><%= purchase.phone_number %></span>
        <span class="purchase-details"><span class="purchase-details-title">Message: </span><%= purchase.message %></span>
      </div>
    </div>
  <% end %>

  <div class="selling">
    <div class="tag">
      <%= image_tag 'icon-shop.svg', alt: 'show icon', class: 'shop-icon' %>
      <span>My selling iPods</span>
    </div>
  </div>
  <% @selling.each do |ipod| %>
    <div class="card-horizontal">
      <div class="d-flex justify-content-between">
        <h3 class="ipod-name"><%= ipod.name %></h3>
        <span class="purchase-price"><%= ipod.price %>€</span>
      </div>
      <div class="d-flex flex-column mb-4">
        <span class="purchase-details"><span class="purchase-details-title">Model: </span><%= ipod.category.name %></span>
        <span class="purchase-details"><span class="purchase-details-title">state: </span><%= ipod.state %></span>
      </div>
    </div>
  <% end %>
</div>